### ISSUE TITLE
Printing does not work and saving gives errors

### ISSUE THREAD

**Issue by PieterDecleer** [SimonDeRidder/Simon-s-html-front-end-for-MPMBs-Character-Record-Sheet#4]
When pressing the print button I get no response and the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at PrintButton (Functions1.js:6319:52)
    at eval (eval at newButton.onclick (app_adapter.js:51:14), <anonymous>:1:1)
    at newButton.onclick (app_adapter.js:51:14)
PrintButton @ Functions1.js:6319
eval @ VM315:1
newButton.onclick @ app_adapter.js:51
```

When saving, the save works, but I get the following error:
`(index):1 The file at 'data:application/json;base64,eyJwYWdlcyI6W3sicGFnZV9udW1iZXIiOiIxIiwicGFnZV9pZCI6InBzdGF0IiwicGFnZV9wcmVmaXgiOiIifSx7InBhZ2VfbnVtYmVyIjoiMiIsInBhZ2VfaWQiOiJwZmVhcSIsInBhZ2VfcHJlZml4IjoiIn0seyJwYWdlX251bWJlciI6IjMiLCJwYWdlX2lkIjoicG5vZmUiLCJwYWdlX3ByZWZpeCI6IiJ9LHsicGFnZV9udW1iZXIiOiI0IiwicGFnZV9pZCI6InBiYWNrIiwicGFnZV9wcmVmaXgiOiIifSx7InBhZ2VfbnVtYmVyIjoiNSIsInBhZ2VfaWQiOiJwbm90ZSIsInBhZ2VfcHJlZml4IjoiUDUuQVNub3Rlcy4ifSx7InBhZ2VfbnVtYmVyIjoiNiIsInBhZ2VfaWQiOiJwc3BlbGxzdGVtcGxfMSIsInBhZ2VfcHJlZml4IjoiUDYuU1Nmcm9udC4ifSx7InBhZ2VfbnVtYmVyIjoiNyIsInBhZ2VfaWQiOiJwcmVmZSIsInBhZ2VfcHJlZml4IjoiIn1dLCJlbGVtZW50cyI6W3sibmFtZSI6IlA0LkFTY29tcC5BU0NvbXAiLCJ2YWx1ZSI6IiJ9LHsibmFtZSI6IlA0LkFTY29tcC5Db21wYW5pb24uT3B0aW9ucyIsInZhbHVlIjoiIiwiZGlzcGxheSI6Mn0seyJuYW1lIjoiUDQuQVNjb21wLkltYWdlLkRuRExvZ28uc2hvcnQiLCJ2YWx1ZSI6IiIsImRpc3BsYXkiOjF9LHsibmFtZSI6IlA0LkFTY29tcC5Db21wLkRlc2MuTmFtZSIsInZhbHVlIjoiIn0seyJuYW1lIjoiUDQuQVNjb21wLkNvbXAuUmFjZSIsInZhbHVlIjoiIiwiaXRlbXMiOlsiIiwiQWJ5c3NhbCBDaGlja2VuIiwiQWlyIEVsZW1lbnRhbCIsIkFsbG9zYXVydXMiLCJBbG1pcmFqIiwiQW5reWxvc2F1cnVzIiwiQW52aWx3cm91Z2h0IFJhcHRvciIsIkFwZSIsIkFwZSwgR2lhbnQiLCJBcnQgRWxlbWVudGFsIE1hc2NvdCIsIkF1cm9jaHMiLCJBd2FrZW5lZCBTaHJ1YiIsIkF3YWtlbmVkIFRyZWUiLCJBd2FrZW5lZCBXaGl0ZSBNb29zZSIsIkF4ZSBCZWFrIiwiQmFib29uIiwiQmFkZ2VyIiwiQmFkZ2VyLCBDYXZlIiwiQmFkZ2VyLCBHaWFudCIsIkJhdCIsIkJhdCwgR2lhbnQiLCJCZWFyLCBCbGFjayIsIkJlYXIsIEJyb3duIiwiQmVhciwgQ2F2ZSIsIkJlYXIsIFBvbGFyIiwiQmVldGxlLCBHaWFudCBGaXJlIiwiQmxhY2sgQmVhciIsIkJsaWdodCwgTmVlZGxlIiwiQmxpZ2h0LCBUd2lnIiwiQmxpZ2h0LCBWaW5lIiwiQmxpbmsgRG9nIiwiQmxvb2QgSGF3ayIsIkJvYXIiLCJCb2FyLCBHaWFudCIsIkJyaXN0bGVkIE1vb3Jib3VuZGVyIiwiQnJvbnRvc2F1cnVzIiwiQnJvd24gQmVhciIsIkNhbWVsIiwiQ2FuYXJ5LCBHaWFudCIsIkNhdCIsIkNhdmUgQmFkZ2VyIiwiQ2F2ZSBCZWFyIiwiQ2VudGlwZWRlLCBHaWFudCIsIkNoaWNrZW4sIEFieXNzYWwiLCJDbGF3Zm9vdCIsIkNsYXkgR29sZW0iLCJDb25zdHJpY3RvciBTbmFrZSIsIkNvdyIsIkNyYWIiLCJDcmFiLCBHaWFudCIsIkNyYWIsIEh1bGtpbmciLCJDcmFuaXVtIFJhdCIsIkNyYXdsaW5nIENsYXciLCJDcmF5ZmlzaCwgR2lhbnQiLCJDcm9jb2RpbGUiLCJDcm9jb2RpbGUsIEdpYW50IiwiQ3JvdyIsIkRlYXRoIERvZyIsIkRlZXAgUm90aFx1ZmZmZCIsIkRlZXIiLCJEZWlub255Y2h1cyIsIkRlbW9zIE1hZ2VuIiwiRGltZXRyb2RvbiIsIkRpcmUgV29sZiIsIkRvZywgQmxpbmsiLCJEb2csIERlYXRoIiwiRG9nLCBTbGVkIiwiRG9scGhpbiIsIkRyYWZ0IEhvcnNlIiwiRHJhZ29uLCBGYWVyaWUiLCJEcmFnb24sIFBzZXVkbyIsIkRyYWdvbmZseSwgR2lhbnQiLCJEdXN0IE1lcGhpdCIsIkVhZ2xlIiwiRWFnbGUsIEdpYW50IiwiRWFydGggRWxlbWVudGFsIiwiRWVsLCBHaWFudCBMaWdodG5pbmciLCJFZWwsIEdpYW50IFNlYSIsIkVlbCwgR2lhbnQgV2hpdGUgTW9yYXkiLCJFZWwsIFNwYWNlIiwiRWxlbWVudGFsLCBBaXIiLCJFbGVtZW50YWwsIEVhcnRoIiwiRWxlbWVudGFsLCBGaXJlIiwiRWxlbWVudGFsLCBXYXRlciIsIkVsZXBoYW50IiwiRWxrIiwiRWxrLCBHaWFudCIsIkZhZXJpZSBEcmFnb24iLCJGYWxjb24iLCJGYXN0aWV0aCIsIkZlbWFsZSBTdGVlZGVyIiwiRmlyZSBFbGVtZW50YWwiLCJGaXNoIiwiRmxlc2ggR29sZW0iLCJGbHksIEdpYW50IiwiRmx5aW5nIE1vbmtleSIsIkZseWluZyBTbmFrZSIsIkZveCIsIkZyYWN0YWwgTWFzY290IiwiRnJvZyIsIkZyb2csIEdpYW50IiwiR2FsdmFuIE1hZ2VuIiwiR2FzIFNwb3JlIiwiR2F6ZXIiLCJHaGFzdCIsIkdob3VsIiwiR2lhbnQgQXBlIiwiR2lhbnQgQmFkZ2VyIiwiR2lhbnQgQmF0IiwiR2lhbnQgQm9hciIsIkdpYW50IENhbmFyeSIsIkdpYW50IENlbnRpcGVkZSIsIkdpYW50IENvbnN0cmljdG9yIFNuYWtlIiwiR2lhbnQgQ29yYWwgU25ha2UiLCJHaWFudCBDcmFiIiwiR2lhbnQgQ3JheWZpc2giLCJHaWFudCBDcm9jb2RpbGUiLCJHaWFudCBEcmFnb25mbHkiLCJHaWFudCBFYWdsZSIsIkdpYW50IEVsayIsIkdpYW50IEZpcmUgQmVldGxlIiwiR2lhbnQgRmx5IiwiR2lhbnQgRnJvZyIsIkdpYW50IEdvYXQiLCJHaWFudCBIeWVuYSIsIkdpYW50IEljZSBUb2FkIiwiR2lhbnQgTGlnaHRuaW5nIEVlbCIsIkdpYW50IExpemFyZCIsIkdpYW50IE9jdG9wdXMiLCJHaWFudCBPd2wiLCJHaWFudCBQb2lzb25vdXMgU25ha2UiLCJHaWFudCBSYXQiLCJHaWFudCBSYXQgKERpc2Vhc2VkKSIsIkdpYW50IFNjb3JwaW9uIiwiR2lhbnQgU2VhIEVlbCIsIkdpYW50IFNlYSBIb3JzZSIsIkdpYW50IFNoYXJrIiwiR2lhbnQgU25haWwiLCJHaWFudCBTbmFwcGluZyBUdXJ0bGUiLCJHaWFudCBTcGFjZSBIYW1zdGVyIiwiR2lhbnQgU3BpZGVyIiwiR2lhbnQgU3VidGVycmFuZWFuIExpemFyZCIsIkdpYW50IFN3YW4iLCJHaWFudCBUb2FkIiwiR2lhbnQgVnVsdHVyZSIsIkdpYW50IFdhbHJ1cyIsIkdpYW50IFdhc3AiLCJHaWFudCBXZWFzZWwiLCJHaWFudCBXaGl0ZSBNb3JheSBFZWwiLCJHaWFudCBXb2xmIFNwaWRlciIsIkdvYXQiLCJHb2F0LCBHaWFudCIsIkdvYXQsIE1vdW50YWluIiwiR29sZW0sIENsYXkiLCJHb2xlbSwgRmxlc2giLCJHb2xlbSwgSXJvbiIsIkdvbGVtLCBTdG9uZSIsIkdyaWZmb24iLCJHdXBweSwgU3BhY2UiLCJIYWRyb3NhdXJ1cyIsIkhhbXN0ZXIsIEdpYW50IFNwYWNlIiwiSGFyZSIsIkhhd2siLCJIaXBwb2dyaWZmIiwiSG9tdW5jdWx1cyIsIkhvcnNlIiwiSG9yc2UsIERyYWZ0IiwiSG9yc2UsIFJpZGluZyIsIkhvcnNlLCBXYXIiLCJIdWxraW5nIENyYWIiLCJIdW50ZXIgU2hhcmsiLCJIeWVuYSIsIkh5ZW5hLCBHaWFudCIsIkh5cG5vcyBNYWdlbiIsIkljZSBNZXBoaXQiLCJJY2UgU3BpZGVyIiwiSW1wIiwiSW5rbGluZyBNYXNjb3QiLCJJcm9uIEdvbGVtIiwiSmFja2FsIiwiSmFjdWxpIiwiS2lsbGVyIFdoYWxlIiwiS251Y2tsZWhlYWQgVHJvdXQiLCJMZW9wYXJkLCBTbm93IiwiTGlvbiIsIkxpemFyZCIsIkxpemFyZCwgR2lhbnQiLCJMaXphcmQsIEdpYW50IFN1YnRlcnJhbmVhbiIsIk1hZ2VuLCBEZW1vcyIsIk1hZ2VuLCBHYWx2YW4iLCJNYWdlbiwgSHlwbm9zIiwiTWFnbWEgTWVwaGl0IiwiTWFsZSBTdGVlZGVyIiwiTWFtbW90aCIsIk1hc2NvdCwgQXJ0IEVsZW1lbnRhbCIsIk1hc2NvdCwgRnJhY3RhbCIsIk1hc2NvdCwgSW5rbGluZyIsIk1hc2NvdCwgUGVzdCIsIk1hc2NvdCwgU3Bpcml0IFN0YXR1ZSIsIk1hc3RpZmYiLCJNZXBoaXQsIER1c3QiLCJNZXBoaXQsIEljZSIsIk1lcGhpdCwgTWFnbWEiLCJNZXBoaXQsIE11ZCIsIk1lcGhpdCwgU21va2UiLCJNZXBoaXQsIFN0ZWFtIiwiTW9sbHltYXdrLCBTcGFjZSIsIk1vbmtleSwgRmx5aW`
[save (1).json](https://github.com/SimonDeRidder/Simon-s-html-front-end-for-MPMBs-Character-Record-Sheet/files/13464053/save.1.json)

**Comment by SimonDeRidder** [comment]
the print button is a known issue, it's next on my todo-list.

Can you include the full error message for the save (particularly the end)? The linked save file loads and re-saves fine on my side.

**Comment by SimonDeRidder** [comment]
This could be a consequence of the Wildshape page not working yet

**Comment by SimonDeRidder** [comment]
fixing print button delegated to https://github.com/SimonDeRidder/Simon-s-html-front-end-for-MPMBs-Character-Record-Sheet/issues/8, let's keep this one for the save/load problem

**Comment by SimonDeRidder** [comment]
Printing fixed in https://github.com/SimonDeRidder/Simon-s-html-front-end-for-MPMBs-Character-Record-Sheet/pull/11

**Comment by SimonDeRidder** [comment]
multiple spells pages fixed in https://github.com/SimonDeRidder/Simon-s-html-front-end-for-MPMBs-Character-Record-Sheet/pull/15, could you test again?
